### ISSUE TITLE
Running CombineFCS on R

### ISSUE THREAD

**Issue by AlexBouz** [tabdelaal/CyTOFmerge#1]
Greeting @tabdelaal and thank you for sharing your code. I have been trying to run the combination of 2 fcs files sharing common markers (for information some channels were not labeled and kept as isotopes numbers), and got stuck at this step (see screenshots), any comment is welcome!
![CombineFCS undefined columns selected](https://user-images.githubusercontent.com/37419030/66719525-10ecc680-edbf-11e9-84a0-a855c80a6cd5.png)
![Data combine 1](https://user-images.githubusercontent.com/37419030/66719526-13e7b700-edbf-11e9-82a7-6a6b2d036c1f.png)
![FCS1data](https://user-images.githubusercontent.com/37419030/66719527-15b17a80-edbf-11e9-8252-0d4bb557671e.png)
![IDX1](https://user-images.githubusercontent.com/37419030/66719528-177b3e00-edbf-11e9-80d1-b07da4422b5f.png)

**Comment by tabdelaal** [comment]
Dear @AlexBouz,

I believe the problem is having all markers shared between the 2 fcs files, as the column size of Data1.nonshared and Data2.nonshared is zero. Which means both fcs files shares all markers and there is nothing to impute between the files. The merging idea relies on having some shared markers, and some unique markers in each file. Are these 2 fcs files produced from two different cytometry panels, but sharing some (not all) markers?
